Backbone integrate matcher config
Data-Backbone/data-backbone pull request #157
Opened 2024-02-29 21:39 UTC by Mikdaam

2024-02-29 21:49 UTC, AxelBelin commented on frontend/src/pages/research-configuration/ResearchConfigForm.jsx
> +            minimalRate: 0,
- Jaro Winkler => 0.7
- Levenshtein => 0.5 ou 0.6
- equals => doit être supérieur à 0.0

2024-02-29 21:50 UTC, AxelBelin requested changes
Méthode saveMatchingConfigs dans ResearchConfigForm : 

- Jaro Winkler => 0.7
- Levenshtein => 0.5 ou 0.6
- equals => doit être supérieur à 0.0

2024-02-29 22:31 UTC, tvdu94 commented on frontend/src/pages/research-configuration/common/CustomInput.jsx
> +const CustomInput = ({name, type, onValueChange}) => {
esapces

2024-02-29 22:31 UTC, tvdu94 commented on frontend/src/pages/research-configuration/common/SelectorAlgorithms.jsx
> +function SelectorAlgorithms({onSelect, title, type}) {
espaces

2024-02-29 22:31 UTC, tvdu94 commented on frontend/src/pages/research-configuration/dataPreview/DataPreviewStep.jsx
> +        fetchData().then();
.then vraiment utile?

2024-02-29 22:31 UTC, tvdu94 commented on frontend/src/pages/research-configuration/matching/MatchingStep.jsx
> +import { Container, Row } from "react-bootstrap";
simple quotes

2024-02-29 22:31 UTC, tvdu94 commented on frontend/src/pages/research-configuration/matching/components/MatrixMatchingConfiguration.jsx
> +import SettingMatchingAlgorithm from "./SettingMatchingAlgorithm";
simple quotes

2024-02-29 22:31 UTC, tvdu94 commented on frontend/src/pages/research-configuration/matching/components/MatrixMatchingConfiguration.jsx
> +                <th/>
utile ou oubli?

2024-02-29 22:31 UTC, tvdu94 commented on frontend/src/pages/research-configuration/matching/components/ModalMatchingConfiguration.jsx
> +import DynamicForm from "../../common/DynamicForm";
simple quotes

2024-02-29 22:31 UTC, tvdu94 commented on frontend/src/pages/research-configuration/matching/components/ModalMatchingConfiguration.jsx
> +const ModalMatchingConfiguration = ({attribute1, attribute2, algorithm, show, handleClose, onSave}) => {
espaces

2024-02-29 22:31 UTC, tvdu94 commented on frontend/src/pages/research-configuration/matching/components/SettingMatchingAlgorithm.jsx
> +import SelectorAlgorithms from "../../common/SelectorAlgorithms";
simple quotes

2024-02-29 22:42 UTC, Mikdaam commented on frontend/src/pages/research-configuration/common/CustomInput.jsx
> +const CustomInput = ({name, type, onValueChange}) => {
serieux !!!

2024-02-29 22:42 UTC, Mikdaam commented on frontend/src/pages/research-configuration/dataPreview/DataPreviewStep.jsx
> +        fetchData().then();
oui

2024-02-29 22:42 UTC, Mikdaam commented on frontend/src/pages/research-configuration/matching/MatchingStep.jsx
> +import { Container, Row } from "react-bootstrap";
c'est pas moi ca

2024-02-29 22:43 UTC, Mikdaam commented on frontend/src/pages/research-configuration/matching/components/MatrixMatchingConfiguration.jsx
> +import SettingMatchingAlgorithm from "./SettingMatchingAlgorithm";
non plus

2024-02-29 22:43 UTC, Mikdaam commented on frontend/src/pages/research-configuration/matching/components/MatrixMatchingConfiguration.jsx
> +                <th/>
utile

2024-03-01 06:35 UTC, AxelBelin approved these changes

2024-03-01 07:06 UTC, merged